version: '3'

services:
  http1:
    build: .
    ports:
      - 1111:3000
    environment:
      HEALTHCHECK_TIMEOUT: 10
      HEALTHCHECK_ADDRESS: "http://http2:3000"
  http2:
    build: .
    ports:
      - 1112:3000
    environment:
      HEALTHCHECK_TIMEOUT: 10
      HEALTHCHECK_ADDRESS: "http://http3:3000"
  http3:
    build: .
    ports:
      - 1113:3000
    environment:
      HEALTHCHECK_TIMEOUT: 10
      HEALTHCHECK_ADDRESS: "http://http1:3000"