
replicaCount: 3

image:
  repository: local/http-server
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

app:
  serverPort: 3000
  healtcheckEnable: "false"
  redisEnable: "true"
  redisAddress: "redis-master.http.svc.cluster.local:6379"